# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"greeting": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://minha12.github.io/nbdev_practice2/"

git_url = "https://github.com/minha12/nbdev_practice2/tree/master/"

def custom_doc_links(name): return None
